source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'LayoutSwiftly_Example', :exclusive => true do
  pod "LayoutSwiftly", :path => "../"
end

target 'LayoutSwiftly_Tests', :exclusive => true do
  pod "LayoutSwiftly", :path => "../"

  pod 'Quick'
end
