language: objective-c
cache: cocoapods
osx_image: xcode7
podfile: Example/Podfile
before_install:
- gem install cocoapods
- gem update cocoapods
- pod install --project-directory=Example
install:
- gem install xcpretty --no-rdoc --no-ri --no-document --quiet
script:
- set -o pipefail && xcodebuild test -workspace Example/LayoutSwiftly.xcworkspace -scheme LayoutSwiftly-Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty -c
- pod lib lint --quick
